package net.ltsoftware.platform.usercenter.dao;

import java.util.List;
import net.ltsoftware.platform.usercenter.model.Order;
import net.ltsoftware.platform.usercenter.model.OrderExample;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_order
     *
     * @mbg.generated Tue Jun 18 10:13:14 CST 2019
     */
    long countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_order
     *
     * @mbg.generated Tue Jun 18 10:13:14 CST 2019
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_order
     *
     * @mbg.generated Tue Jun 18 10:13:14 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_order
     *
     * @mbg.generated Tue Jun 18 10:13:14 CST 2019
     */
    int insert(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_order
     *
     * @mbg.generated Tue Jun 18 10:13:14 CST 2019
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_order
     *
     * @mbg.generated Tue Jun 18 10:13:14 CST 2019
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_order
     *
     * @mbg.generated Tue Jun 18 10:13:14 CST 2019
     */
    Order selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_order
     *
     * @mbg.generated Tue Jun 18 10:13:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_order
     *
     * @mbg.generated Tue Jun 18 10:13:14 CST 2019
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_order
     *
     * @mbg.generated Tue Jun 18 10:13:14 CST 2019
     */
    int updateByPrimaryKeySelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_order
     *
     * @mbg.generated Tue Jun 18 10:13:14 CST 2019
     */
    int updateByPrimaryKey(Order record);
}