@startuml

html -> user_center: get openId
user_center -> weixin_mp: get openId
weixin_mp -> user_center: openId
user_center -> html: openId
html -> saas: buy
saas -> saas: create order
saas -> user_center: pay
user_center -> user_center: create trade
user_center -> wxpay: unified order
wxpay -> user_center: prepayId
user_center -> user_center: build pay params
user_center -> saas: pay params
saas -> html: pay params
html -> wxpay: invoke pay
wxpay -> user_center: success notify
user_center -> user_center: update trade status
user_center -> saas: subsystem callback
saas -> saas: update order
html -> saas: check order
html -> html: redirect detail page

@enduml