#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  # typeAliasesPackage: net.ltsoftware.platform.usercenter.model
  mapperLocations: classpath:mapper/*.xml

security:
  excludeUrls:
    - /oauth/qqurl
    - /oauth/qqcallback

payment:
  alipay_conf:
    url: https://openapi.alipay.com/gateway.do
    appid: 2019061065521285
    app_private_key: MIIEwAIBADANBgkqhkiG9w0BAQEFAASCBKowggSmAgEAAoIBAQC4CmIZFE6PdssVKh5YIQmuH87Yv/8dLCjU3E7H+1SWPEGWbDeMJPY4bazebmmgaTxULk+3C6ORLZ4G81yEntEgXMmZG9m8L+Dd4wXIKGU/CMacfxQHhF0u4Avg33gositPvXInm5n2FHrFfbHWVS7NYNzvWEOpd17DWut3siujh20OW2N5l5JNAmdN+2jNj+8ne8m+2z3z7DxKLNEBYiRuvDo2RkcTQTF1lQ3V5mdePc94DERZKv9qlwAvzy98P0ihGv0uE9y1f+1xEClpBkcjYlDu1q+dAZ1JHeQCIPUvCp7Afruii3TEfqnObX19zRT9lnqjkxZyhf/a2fwH/pA1AgMBAAECggEBALGZO38uLH2fSmzbHzs2bov8n/RkmwCA28pF6zRq4f60mSpatePky0I6/EYN0Jp+0zv9EOn4Lljr54KXmCFWzUJoqBa7XIuQvHQDH1I/QSzqABeHPkHexrl0daIEpITJIqipjZ6RNqrUqoEoQdQukaKZpbrGt0yzJ9xnQbFZW2lKpEI6riFe42BcPUSufJAUrEW9jTYr95dkCw0cj9bi/hE3s64IxmtM32XaczE4oI9UoDch6AzahPsaIfdC2do6Q+wD6Bo3f2NH5GiT+y1fblLs3ZZuy0s4fYAkx011BrBdND72psTIV4qa4jX9ve93XZ/tiuNpfxEt25iPHvyjBeECgYEA5Jtou0PABdLVszJ0BPxH1g5UDQfkuA53APWE++Q/37BbE06sk1K/4iA/Y1VwISqKJbYaAwKCBrCj+Ef/PsC1U+6UpACcKKqBDhxfLaM3OM8aTkK+RBkLvkHV74BrploWLkpc2Z8N++xALLElnc/BXErm99q6d6qQSBRN7POfhJkCgYEAzhfiDBNJAPMs5TJMluU4dKKkY0MBuG24F8PxAp5FHOQ2P7kqU7UoYRSRtkpiEW8ZgWrcGK21FmpADLJVGlxS/0gLyURU5a3O6Qs4g/t9RAj4QMUBJlt+okupJ67cafWLdIEt7zprXVTcQWu6lTTGL8gGe/4N0c9aAD0wAge6zf0CgYEAvO+EO2DfDvEVFSkZohUu+caVyL9BVKz/xZck9VnLQIBshSR8lLXLSIQGX355Ua/qxQgfr2UfOZA7tDMszRxPwLJpvrGSXjmst5DTSNCgDx97Sjr3LSjV/8RBn9OvJKlHs7JZ0rIVyKOU1lsCD89oq3JsOWRYwBYDcM73KGKg7+ECgYEAtKsjMsrFONv1A4ewtKeFcloSGiJno7IrrEnNQipVFBrLo9lDTdaF63UIt/FFP1tR1K5E/C1rjpbeR0Meb9l3uOsDyhDpC9/uf0Wi6bDSA46Jct5BP8r9nHEPfQZBm3HyKtQD3LAt5se5vnAeRSbahpCnfpMcsk0/7O225FC6ZlECgYEAtHpRCqi1mpmT902mvKLUl0r38ecFra2WiUXgtiAyK4znl1bjqrPUNTH7W/EyNMaTiGdKOx20AHd1EFoNY7YZLq0dtn603PSH46MBPZmizhpIdszzJ6ZjR0ijCT7WeBEXMLj/QFFYIzn3Xy6u38RNWPyWCrQWXCotY5DPlDSGQec=
    format: json
    charset: UTF-8
    alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuApiGRROj3bLFSoeWCEJrh/O2L//HSwo1NxOx/tUljxBlmw3jCT2OG2s3m5poGk8VC5PtwujkS2eBvNchJ7RIFzJmRvZvC/g3eMFyChlPwjGnH8UB4RdLuAL4N94KLIrT71yJ5uZ9hR6xX2x1lUuzWDc71hDqXdew1rrd7Iro4dtDltjeZeSTQJnTftozY/vJ3vJvts98+w8SizRAWIkbrw6NkZHE0ExdZUN1eZnXj3PeAxEWSr/apcAL88vfD9IoRr9LhPctX/tcRApaQZHI2JQ7tavnQGdSR3kAiD1LwqewH67oot0xH6pzm19fc0U/ZZ6o5MWcoX/2tn8B/6QNQIDAQAB
    sign_type: RSA2

---

#本地配置
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/platform
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#jedis配置
jedis:
  pool:
    host: 127.0.0.1
    port: 6379
    config:
      maxTotal: 20
      maxIdle: 10
      maxWaitMillis: 100000

---

#开发服务器配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://rm-wz96zu147r13k6kk3.mysql.rds.aliyuncs.com:3306/platform
    username: lt_dev
    password: rVMBcz4+5JDWfg
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#redis配置
jedis:
  pool:
    host: r-wz9nogivnknogmkk30.redis.rds.aliyuncs.com
    password: zPWkmOQ05KiD0Q
    port: 6379
    timeout: 60
    config:
      maxTotal: 200
      maxIdle: 100
      maxWaitMillis: 100000

