#默认使用配置
spring:
  profiles:
    active: local

#公共配置与profiles选择无关
mybatis:
  # typeAliasesPackage: net.ltsoftware.usercenter.model
  mapperLocations: classpath:mapper/*.xml

---

server:
  port: 6443
#  ssl:
#    key-store: E:\IdeaProjects\platform\saas\mykeystore.jks
#    key-store-password: S0kiShgsZwAk
#    keyAlias: springboot
#    protocol: TLS
#    key-password: S0kiShgsZwAk
#    enabled: true
#  max-http-header-size: 8192

#本地配置
spring:
  profiles: local-pc
  datasource:
    url: jdbc:mysql://localhost:3306/dev-platform
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: MYSQL
    show-sql: true

#logging:
#  level:
#    net.ltsoftware.saas.dao: trace


#jedis配置
jedis:
  pool:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 60
    config:
      maxTotal: 20
      maxIdle: 10
      maxWaitMillis: 100000

---

server:
  port: 6443
#  ssl:
#    key-store: /Users/apple/IdeaProjects/platform/saas/mykeystore.jks
#    key-store-password: S0kiShgsZwAk
#    keyAlias: springboot
#    protocol: TLS
#    key-password: S0kiShgsZwAk
#    enabled: true
#  max-http-header-size: 8192

#本地配置
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/dev-platform
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database: MYSQL
    show-sql: true

#logging:
#  level:
#    net.ltsoftware.usercenter.dao: trace


#jedis配置
jedis:
  pool:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 60
    config:
      maxTotal: 20
      maxIdle: 10
      maxWaitMillis: 100000

---

#开发服务器配置
server:
  port: 56443
  ssl:
    key-store: /etc/letsencrypt/live/ltsoftware.net/mykeystore.jks
    key-store-password: S0kiShgsZwAk
    keyAlias: springboot
    protocol: TLS
    key-password: S0kiShgsZwAk
    enabled: true
  max-http-header-size: 8192

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://rm-wz96zu147r13k6kk3.mysql.rds.aliyuncs.com:3306/dev-platform
    username: lt_dev
    password: rVMBcz4+5JDWfg
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#redis配置
jedis:
  pool:
    host: 127.0.0.1
    password: 123456
    port: 6379
    timeout: 60
    config:
      maxTotal: 200
      maxIdle: 100
      maxWaitMillis: 100000

#logging:
#  level:
#    net.ltsoftware.usercenter: trace

---

#生产服务器配置
server:
  port: 6443
  ssl:
    key-store: /etc/letsencrypt/live/ltsoftware.net/mykeystore.jks
    key-store-password: S0kiShgsZwAk
    keyAlias: springboot
    protocol: TLS
    key-password: S0kiShgsZwAk
    enabled: true
  max-http-header-size: 8192

spring:
  profiles: product
  datasource:
    url: jdbc:mysql://rm-wz96zu147r13k6kk3.mysql.rds.aliyuncs.com:3306/platform
    username: lt_dev
    password: rVMBcz4+5JDWfg
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

#redis配置
jedis:
  pool:
    host: r-wz9nogivnknogmkk30.redis.rds.aliyuncs.com
    password: zPWkmOQ05KiD0Q
    port: 6379
    timeout: 60
    config:
      maxTotal: 200
      maxIdle: 100
      maxWaitMillis: 100000

#logging:
#  level:
#    net.ltsoftware.usercenter: trace
