package net.ltsoftware.usercenter.model;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.user_id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.orig_amount
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private Long origAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.amount
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.create_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private String createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.update_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private String updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.product_id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.type1_id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private Integer type1Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.type2_id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private Integer type2Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.status
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.valid_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private String validTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.is_valid
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private Integer isValid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.is_deleted
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private Integer isDeleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.expired_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private String expiredTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.deleted_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private String deletedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.trade_no
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private String tradeNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.trade_no_3rd
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private String tradeNo3rd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_order.pay_channel
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    private String payChannel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.id
     *
     * @return the value of acc_order.id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.id
     *
     * @param id the value for acc_order.id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.user_id
     *
     * @return the value of acc_order.user_id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.user_id
     *
     * @param userId the value for acc_order.user_id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.orig_amount
     *
     * @return the value of acc_order.orig_amount
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public Long getOrigAmount() {
        return origAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.orig_amount
     *
     * @param origAmount the value for acc_order.orig_amount
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setOrigAmount(Long origAmount) {
        this.origAmount = origAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.amount
     *
     * @return the value of acc_order.amount
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.amount
     *
     * @param amount the value for acc_order.amount
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.create_time
     *
     * @return the value of acc_order.create_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.create_time
     *
     * @param createTime the value for acc_order.create_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.update_time
     *
     * @return the value of acc_order.update_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.update_time
     *
     * @param updateTime the value for acc_order.update_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.product_id
     *
     * @return the value of acc_order.product_id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.product_id
     *
     * @param productId the value for acc_order.product_id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.type1_id
     *
     * @return the value of acc_order.type1_id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public Integer getType1Id() {
        return type1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.type1_id
     *
     * @param type1Id the value for acc_order.type1_id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setType1Id(Integer type1Id) {
        this.type1Id = type1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.type2_id
     *
     * @return the value of acc_order.type2_id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public Integer getType2Id() {
        return type2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.type2_id
     *
     * @param type2Id the value for acc_order.type2_id
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setType2Id(Integer type2Id) {
        this.type2Id = type2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.status
     *
     * @return the value of acc_order.status
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.status
     *
     * @param status the value for acc_order.status
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.valid_time
     *
     * @return the value of acc_order.valid_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public String getValidTime() {
        return validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.valid_time
     *
     * @param validTime the value for acc_order.valid_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setValidTime(String validTime) {
        this.validTime = validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.is_valid
     *
     * @return the value of acc_order.is_valid
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.is_valid
     *
     * @param isValid the value for acc_order.is_valid
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.is_deleted
     *
     * @return the value of acc_order.is_deleted
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.is_deleted
     *
     * @param isDeleted the value for acc_order.is_deleted
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.expired_time
     *
     * @return the value of acc_order.expired_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public String getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.expired_time
     *
     * @param expiredTime the value for acc_order.expired_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setExpiredTime(String expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.deleted_time
     *
     * @return the value of acc_order.deleted_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public String getDeletedTime() {
        return deletedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.deleted_time
     *
     * @param deletedTime the value for acc_order.deleted_time
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setDeletedTime(String deletedTime) {
        this.deletedTime = deletedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.trade_no
     *
     * @return the value of acc_order.trade_no
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.trade_no
     *
     * @param tradeNo the value for acc_order.trade_no
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.trade_no_3rd
     *
     * @return the value of acc_order.trade_no_3rd
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public String getTradeNo3rd() {
        return tradeNo3rd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.trade_no_3rd
     *
     * @param tradeNo3rd the value for acc_order.trade_no_3rd
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setTradeNo3rd(String tradeNo3rd) {
        this.tradeNo3rd = tradeNo3rd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_order.pay_channel
     *
     * @return the value of acc_order.pay_channel
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public String getPayChannel() {
        return payChannel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_order.pay_channel
     *
     * @param payChannel the value for acc_order.pay_channel
     *
     * @mbg.generated Tue Aug 06 23:59:30 CST 2019
     */
    public void setPayChannel(String payChannel) {
        this.payChannel = payChannel;
    }
}