package net.ltsoftware.usercenter.model;

import java.math.BigDecimal;
import java.util.Date;

public class PayOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.id
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.pay_order_id
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String payOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.mch_no
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String mchNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.sub_mch_id
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String subMchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.mch_order_list
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String mchOrderList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.softType
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String softtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.isv_no
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String isvNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.app_id
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.mch_name
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String mchName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.mch_type
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Byte mchType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.mch_order_no
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String mchOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.if_code
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String ifCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.way_code
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String wayCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.amount
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.mch_fee_rate
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private BigDecimal mchFeeRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.mch_fee_amount
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Long mchFeeAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.currency
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String currency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.state
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.notify_state
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Byte notifyState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.client_ip
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String clientIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.subject
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String subject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.body
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String body;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.channel_extra
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String channelExtra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.channel_user
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String channelUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.channel_order_no
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String channelOrderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.refund_state
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Byte refundState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.refund_times
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Integer refundTimes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.refund_amount
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Long refundAmount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.division_mode
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Byte divisionMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.division_state
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Byte divisionState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.division_last_time
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Date divisionLastTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.err_code
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String errCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.err_msg
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String errMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.ext_param
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String extParam;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.notify_url
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String notifyUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.return_url
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String returnUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.expired_time
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Date expiredTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.success_time
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Date successTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.created_at
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.updated_at
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_pay_order.notify_data
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    private String notifyData;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.id
     *
     * @return the value of t_pay_order.id
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.id
     *
     * @param id the value for t_pay_order.id
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.pay_order_id
     *
     * @return the value of t_pay_order.pay_order_id
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getPayOrderId() {
        return payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.pay_order_id
     *
     * @param payOrderId the value for t_pay_order.pay_order_id
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setPayOrderId(String payOrderId) {
        this.payOrderId = payOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.mch_no
     *
     * @return the value of t_pay_order.mch_no
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getMchNo() {
        return mchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.mch_no
     *
     * @param mchNo the value for t_pay_order.mch_no
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setMchNo(String mchNo) {
        this.mchNo = mchNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.sub_mch_id
     *
     * @return the value of t_pay_order.sub_mch_id
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getSubMchId() {
        return subMchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.sub_mch_id
     *
     * @param subMchId the value for t_pay_order.sub_mch_id
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setSubMchId(String subMchId) {
        this.subMchId = subMchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.mch_order_list
     *
     * @return the value of t_pay_order.mch_order_list
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getMchOrderList() {
        return mchOrderList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.mch_order_list
     *
     * @param mchOrderList the value for t_pay_order.mch_order_list
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setMchOrderList(String mchOrderList) {
        this.mchOrderList = mchOrderList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.softType
     *
     * @return the value of t_pay_order.softType
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getSofttype() {
        return softtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.softType
     *
     * @param softtype the value for t_pay_order.softType
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setSofttype(String softtype) {
        this.softtype = softtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.isv_no
     *
     * @return the value of t_pay_order.isv_no
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getIsvNo() {
        return isvNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.isv_no
     *
     * @param isvNo the value for t_pay_order.isv_no
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setIsvNo(String isvNo) {
        this.isvNo = isvNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.app_id
     *
     * @return the value of t_pay_order.app_id
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.app_id
     *
     * @param appId the value for t_pay_order.app_id
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.mch_name
     *
     * @return the value of t_pay_order.mch_name
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getMchName() {
        return mchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.mch_name
     *
     * @param mchName the value for t_pay_order.mch_name
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setMchName(String mchName) {
        this.mchName = mchName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.mch_type
     *
     * @return the value of t_pay_order.mch_type
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Byte getMchType() {
        return mchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.mch_type
     *
     * @param mchType the value for t_pay_order.mch_type
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setMchType(Byte mchType) {
        this.mchType = mchType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.mch_order_no
     *
     * @return the value of t_pay_order.mch_order_no
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getMchOrderNo() {
        return mchOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.mch_order_no
     *
     * @param mchOrderNo the value for t_pay_order.mch_order_no
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setMchOrderNo(String mchOrderNo) {
        this.mchOrderNo = mchOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.if_code
     *
     * @return the value of t_pay_order.if_code
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getIfCode() {
        return ifCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.if_code
     *
     * @param ifCode the value for t_pay_order.if_code
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setIfCode(String ifCode) {
        this.ifCode = ifCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.way_code
     *
     * @return the value of t_pay_order.way_code
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getWayCode() {
        return wayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.way_code
     *
     * @param wayCode the value for t_pay_order.way_code
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setWayCode(String wayCode) {
        this.wayCode = wayCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.amount
     *
     * @return the value of t_pay_order.amount
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.amount
     *
     * @param amount the value for t_pay_order.amount
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.mch_fee_rate
     *
     * @return the value of t_pay_order.mch_fee_rate
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public BigDecimal getMchFeeRate() {
        return mchFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.mch_fee_rate
     *
     * @param mchFeeRate the value for t_pay_order.mch_fee_rate
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setMchFeeRate(BigDecimal mchFeeRate) {
        this.mchFeeRate = mchFeeRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.mch_fee_amount
     *
     * @return the value of t_pay_order.mch_fee_amount
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Long getMchFeeAmount() {
        return mchFeeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.mch_fee_amount
     *
     * @param mchFeeAmount the value for t_pay_order.mch_fee_amount
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setMchFeeAmount(Long mchFeeAmount) {
        this.mchFeeAmount = mchFeeAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.currency
     *
     * @return the value of t_pay_order.currency
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.currency
     *
     * @param currency the value for t_pay_order.currency
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setCurrency(String currency) {
        this.currency = currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.state
     *
     * @return the value of t_pay_order.state
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.state
     *
     * @param state the value for t_pay_order.state
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.notify_state
     *
     * @return the value of t_pay_order.notify_state
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Byte getNotifyState() {
        return notifyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.notify_state
     *
     * @param notifyState the value for t_pay_order.notify_state
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setNotifyState(Byte notifyState) {
        this.notifyState = notifyState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.client_ip
     *
     * @return the value of t_pay_order.client_ip
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getClientIp() {
        return clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.client_ip
     *
     * @param clientIp the value for t_pay_order.client_ip
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.subject
     *
     * @return the value of t_pay_order.subject
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.subject
     *
     * @param subject the value for t_pay_order.subject
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.body
     *
     * @return the value of t_pay_order.body
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.body
     *
     * @param body the value for t_pay_order.body
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.channel_extra
     *
     * @return the value of t_pay_order.channel_extra
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getChannelExtra() {
        return channelExtra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.channel_extra
     *
     * @param channelExtra the value for t_pay_order.channel_extra
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setChannelExtra(String channelExtra) {
        this.channelExtra = channelExtra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.channel_user
     *
     * @return the value of t_pay_order.channel_user
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getChannelUser() {
        return channelUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.channel_user
     *
     * @param channelUser the value for t_pay_order.channel_user
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setChannelUser(String channelUser) {
        this.channelUser = channelUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.channel_order_no
     *
     * @return the value of t_pay_order.channel_order_no
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getChannelOrderNo() {
        return channelOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.channel_order_no
     *
     * @param channelOrderNo the value for t_pay_order.channel_order_no
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setChannelOrderNo(String channelOrderNo) {
        this.channelOrderNo = channelOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.refund_state
     *
     * @return the value of t_pay_order.refund_state
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Byte getRefundState() {
        return refundState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.refund_state
     *
     * @param refundState the value for t_pay_order.refund_state
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setRefundState(Byte refundState) {
        this.refundState = refundState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.refund_times
     *
     * @return the value of t_pay_order.refund_times
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Integer getRefundTimes() {
        return refundTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.refund_times
     *
     * @param refundTimes the value for t_pay_order.refund_times
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setRefundTimes(Integer refundTimes) {
        this.refundTimes = refundTimes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.refund_amount
     *
     * @return the value of t_pay_order.refund_amount
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Long getRefundAmount() {
        return refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.refund_amount
     *
     * @param refundAmount the value for t_pay_order.refund_amount
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setRefundAmount(Long refundAmount) {
        this.refundAmount = refundAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.division_mode
     *
     * @return the value of t_pay_order.division_mode
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Byte getDivisionMode() {
        return divisionMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.division_mode
     *
     * @param divisionMode the value for t_pay_order.division_mode
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setDivisionMode(Byte divisionMode) {
        this.divisionMode = divisionMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.division_state
     *
     * @return the value of t_pay_order.division_state
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Byte getDivisionState() {
        return divisionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.division_state
     *
     * @param divisionState the value for t_pay_order.division_state
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setDivisionState(Byte divisionState) {
        this.divisionState = divisionState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.division_last_time
     *
     * @return the value of t_pay_order.division_last_time
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Date getDivisionLastTime() {
        return divisionLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.division_last_time
     *
     * @param divisionLastTime the value for t_pay_order.division_last_time
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setDivisionLastTime(Date divisionLastTime) {
        this.divisionLastTime = divisionLastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.err_code
     *
     * @return the value of t_pay_order.err_code
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getErrCode() {
        return errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.err_code
     *
     * @param errCode the value for t_pay_order.err_code
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setErrCode(String errCode) {
        this.errCode = errCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.err_msg
     *
     * @return the value of t_pay_order.err_msg
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getErrMsg() {
        return errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.err_msg
     *
     * @param errMsg the value for t_pay_order.err_msg
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setErrMsg(String errMsg) {
        this.errMsg = errMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.ext_param
     *
     * @return the value of t_pay_order.ext_param
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getExtParam() {
        return extParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.ext_param
     *
     * @param extParam the value for t_pay_order.ext_param
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setExtParam(String extParam) {
        this.extParam = extParam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.notify_url
     *
     * @return the value of t_pay_order.notify_url
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getNotifyUrl() {
        return notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.notify_url
     *
     * @param notifyUrl the value for t_pay_order.notify_url
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.return_url
     *
     * @return the value of t_pay_order.return_url
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getReturnUrl() {
        return returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.return_url
     *
     * @param returnUrl the value for t_pay_order.return_url
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.expired_time
     *
     * @return the value of t_pay_order.expired_time
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Date getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.expired_time
     *
     * @param expiredTime the value for t_pay_order.expired_time
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.success_time
     *
     * @return the value of t_pay_order.success_time
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Date getSuccessTime() {
        return successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.success_time
     *
     * @param successTime the value for t_pay_order.success_time
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setSuccessTime(Date successTime) {
        this.successTime = successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.created_at
     *
     * @return the value of t_pay_order.created_at
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.created_at
     *
     * @param createdAt the value for t_pay_order.created_at
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.updated_at
     *
     * @return the value of t_pay_order.updated_at
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.updated_at
     *
     * @param updatedAt the value for t_pay_order.updated_at
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_pay_order.notify_data
     *
     * @return the value of t_pay_order.notify_data
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getNotifyData() {
        return notifyData;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_pay_order.notify_data
     *
     * @param notifyData the value for t_pay_order.notify_data
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setNotifyData(String notifyData) {
        this.notifyData = notifyData;
    }
}