package net.ltsoftware.usercenter.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PayOrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public PayOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPayOrderIdIsNull() {
            addCriterion("pay_order_id is null");
            return (Criteria) this;
        }

        public Criteria andPayOrderIdIsNotNull() {
            addCriterion("pay_order_id is not null");
            return (Criteria) this;
        }

        public Criteria andPayOrderIdEqualTo(String value) {
            addCriterion("pay_order_id =", value, "payOrderId");
            return (Criteria) this;
        }

        public Criteria andPayOrderIdNotEqualTo(String value) {
            addCriterion("pay_order_id <>", value, "payOrderId");
            return (Criteria) this;
        }

        public Criteria andPayOrderIdGreaterThan(String value) {
            addCriterion("pay_order_id >", value, "payOrderId");
            return (Criteria) this;
        }

        public Criteria andPayOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("pay_order_id >=", value, "payOrderId");
            return (Criteria) this;
        }

        public Criteria andPayOrderIdLessThan(String value) {
            addCriterion("pay_order_id <", value, "payOrderId");
            return (Criteria) this;
        }

        public Criteria andPayOrderIdLessThanOrEqualTo(String value) {
            addCriterion("pay_order_id <=", value, "payOrderId");
            return (Criteria) this;
        }

        public Criteria andPayOrderIdLike(String value) {
            addCriterion("pay_order_id like", value, "payOrderId");
            return (Criteria) this;
        }

        public Criteria andPayOrderIdNotLike(String value) {
            addCriterion("pay_order_id not like", value, "payOrderId");
            return (Criteria) this;
        }

        public Criteria andPayOrderIdIn(List<String> values) {
            addCriterion("pay_order_id in", values, "payOrderId");
            return (Criteria) this;
        }

        public Criteria andPayOrderIdNotIn(List<String> values) {
            addCriterion("pay_order_id not in", values, "payOrderId");
            return (Criteria) this;
        }

        public Criteria andPayOrderIdBetween(String value1, String value2) {
            addCriterion("pay_order_id between", value1, value2, "payOrderId");
            return (Criteria) this;
        }

        public Criteria andPayOrderIdNotBetween(String value1, String value2) {
            addCriterion("pay_order_id not between", value1, value2, "payOrderId");
            return (Criteria) this;
        }

        public Criteria andMchNoIsNull() {
            addCriterion("mch_no is null");
            return (Criteria) this;
        }

        public Criteria andMchNoIsNotNull() {
            addCriterion("mch_no is not null");
            return (Criteria) this;
        }

        public Criteria andMchNoEqualTo(String value) {
            addCriterion("mch_no =", value, "mchNo");
            return (Criteria) this;
        }

        public Criteria andMchNoNotEqualTo(String value) {
            addCriterion("mch_no <>", value, "mchNo");
            return (Criteria) this;
        }

        public Criteria andMchNoGreaterThan(String value) {
            addCriterion("mch_no >", value, "mchNo");
            return (Criteria) this;
        }

        public Criteria andMchNoGreaterThanOrEqualTo(String value) {
            addCriterion("mch_no >=", value, "mchNo");
            return (Criteria) this;
        }

        public Criteria andMchNoLessThan(String value) {
            addCriterion("mch_no <", value, "mchNo");
            return (Criteria) this;
        }

        public Criteria andMchNoLessThanOrEqualTo(String value) {
            addCriterion("mch_no <=", value, "mchNo");
            return (Criteria) this;
        }

        public Criteria andMchNoLike(String value) {
            addCriterion("mch_no like", value, "mchNo");
            return (Criteria) this;
        }

        public Criteria andMchNoNotLike(String value) {
            addCriterion("mch_no not like", value, "mchNo");
            return (Criteria) this;
        }

        public Criteria andMchNoIn(List<String> values) {
            addCriterion("mch_no in", values, "mchNo");
            return (Criteria) this;
        }

        public Criteria andMchNoNotIn(List<String> values) {
            addCriterion("mch_no not in", values, "mchNo");
            return (Criteria) this;
        }

        public Criteria andMchNoBetween(String value1, String value2) {
            addCriterion("mch_no between", value1, value2, "mchNo");
            return (Criteria) this;
        }

        public Criteria andMchNoNotBetween(String value1, String value2) {
            addCriterion("mch_no not between", value1, value2, "mchNo");
            return (Criteria) this;
        }

        public Criteria andSubMchIdIsNull() {
            addCriterion("sub_mch_id is null");
            return (Criteria) this;
        }

        public Criteria andSubMchIdIsNotNull() {
            addCriterion("sub_mch_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubMchIdEqualTo(String value) {
            addCriterion("sub_mch_id =", value, "subMchId");
            return (Criteria) this;
        }

        public Criteria andSubMchIdNotEqualTo(String value) {
            addCriterion("sub_mch_id <>", value, "subMchId");
            return (Criteria) this;
        }

        public Criteria andSubMchIdGreaterThan(String value) {
            addCriterion("sub_mch_id >", value, "subMchId");
            return (Criteria) this;
        }

        public Criteria andSubMchIdGreaterThanOrEqualTo(String value) {
            addCriterion("sub_mch_id >=", value, "subMchId");
            return (Criteria) this;
        }

        public Criteria andSubMchIdLessThan(String value) {
            addCriterion("sub_mch_id <", value, "subMchId");
            return (Criteria) this;
        }

        public Criteria andSubMchIdLessThanOrEqualTo(String value) {
            addCriterion("sub_mch_id <=", value, "subMchId");
            return (Criteria) this;
        }

        public Criteria andSubMchIdLike(String value) {
            addCriterion("sub_mch_id like", value, "subMchId");
            return (Criteria) this;
        }

        public Criteria andSubMchIdNotLike(String value) {
            addCriterion("sub_mch_id not like", value, "subMchId");
            return (Criteria) this;
        }

        public Criteria andSubMchIdIn(List<String> values) {
            addCriterion("sub_mch_id in", values, "subMchId");
            return (Criteria) this;
        }

        public Criteria andSubMchIdNotIn(List<String> values) {
            addCriterion("sub_mch_id not in", values, "subMchId");
            return (Criteria) this;
        }

        public Criteria andSubMchIdBetween(String value1, String value2) {
            addCriterion("sub_mch_id between", value1, value2, "subMchId");
            return (Criteria) this;
        }

        public Criteria andSubMchIdNotBetween(String value1, String value2) {
            addCriterion("sub_mch_id not between", value1, value2, "subMchId");
            return (Criteria) this;
        }

        public Criteria andMchOrderListIsNull() {
            addCriterion("mch_order_list is null");
            return (Criteria) this;
        }

        public Criteria andMchOrderListIsNotNull() {
            addCriterion("mch_order_list is not null");
            return (Criteria) this;
        }

        public Criteria andMchOrderListEqualTo(String value) {
            addCriterion("mch_order_list =", value, "mchOrderList");
            return (Criteria) this;
        }

        public Criteria andMchOrderListNotEqualTo(String value) {
            addCriterion("mch_order_list <>", value, "mchOrderList");
            return (Criteria) this;
        }

        public Criteria andMchOrderListGreaterThan(String value) {
            addCriterion("mch_order_list >", value, "mchOrderList");
            return (Criteria) this;
        }

        public Criteria andMchOrderListGreaterThanOrEqualTo(String value) {
            addCriterion("mch_order_list >=", value, "mchOrderList");
            return (Criteria) this;
        }

        public Criteria andMchOrderListLessThan(String value) {
            addCriterion("mch_order_list <", value, "mchOrderList");
            return (Criteria) this;
        }

        public Criteria andMchOrderListLessThanOrEqualTo(String value) {
            addCriterion("mch_order_list <=", value, "mchOrderList");
            return (Criteria) this;
        }

        public Criteria andMchOrderListLike(String value) {
            addCriterion("mch_order_list like", value, "mchOrderList");
            return (Criteria) this;
        }

        public Criteria andMchOrderListNotLike(String value) {
            addCriterion("mch_order_list not like", value, "mchOrderList");
            return (Criteria) this;
        }

        public Criteria andMchOrderListIn(List<String> values) {
            addCriterion("mch_order_list in", values, "mchOrderList");
            return (Criteria) this;
        }

        public Criteria andMchOrderListNotIn(List<String> values) {
            addCriterion("mch_order_list not in", values, "mchOrderList");
            return (Criteria) this;
        }

        public Criteria andMchOrderListBetween(String value1, String value2) {
            addCriterion("mch_order_list between", value1, value2, "mchOrderList");
            return (Criteria) this;
        }

        public Criteria andMchOrderListNotBetween(String value1, String value2) {
            addCriterion("mch_order_list not between", value1, value2, "mchOrderList");
            return (Criteria) this;
        }

        public Criteria andSofttypeIsNull() {
            addCriterion("softType is null");
            return (Criteria) this;
        }

        public Criteria andSofttypeIsNotNull() {
            addCriterion("softType is not null");
            return (Criteria) this;
        }

        public Criteria andSofttypeEqualTo(String value) {
            addCriterion("softType =", value, "softtype");
            return (Criteria) this;
        }

        public Criteria andSofttypeNotEqualTo(String value) {
            addCriterion("softType <>", value, "softtype");
            return (Criteria) this;
        }

        public Criteria andSofttypeGreaterThan(String value) {
            addCriterion("softType >", value, "softtype");
            return (Criteria) this;
        }

        public Criteria andSofttypeGreaterThanOrEqualTo(String value) {
            addCriterion("softType >=", value, "softtype");
            return (Criteria) this;
        }

        public Criteria andSofttypeLessThan(String value) {
            addCriterion("softType <", value, "softtype");
            return (Criteria) this;
        }

        public Criteria andSofttypeLessThanOrEqualTo(String value) {
            addCriterion("softType <=", value, "softtype");
            return (Criteria) this;
        }

        public Criteria andSofttypeLike(String value) {
            addCriterion("softType like", value, "softtype");
            return (Criteria) this;
        }

        public Criteria andSofttypeNotLike(String value) {
            addCriterion("softType not like", value, "softtype");
            return (Criteria) this;
        }

        public Criteria andSofttypeIn(List<String> values) {
            addCriterion("softType in", values, "softtype");
            return (Criteria) this;
        }

        public Criteria andSofttypeNotIn(List<String> values) {
            addCriterion("softType not in", values, "softtype");
            return (Criteria) this;
        }

        public Criteria andSofttypeBetween(String value1, String value2) {
            addCriterion("softType between", value1, value2, "softtype");
            return (Criteria) this;
        }

        public Criteria andSofttypeNotBetween(String value1, String value2) {
            addCriterion("softType not between", value1, value2, "softtype");
            return (Criteria) this;
        }

        public Criteria andIsvNoIsNull() {
            addCriterion("isv_no is null");
            return (Criteria) this;
        }

        public Criteria andIsvNoIsNotNull() {
            addCriterion("isv_no is not null");
            return (Criteria) this;
        }

        public Criteria andIsvNoEqualTo(String value) {
            addCriterion("isv_no =", value, "isvNo");
            return (Criteria) this;
        }

        public Criteria andIsvNoNotEqualTo(String value) {
            addCriterion("isv_no <>", value, "isvNo");
            return (Criteria) this;
        }

        public Criteria andIsvNoGreaterThan(String value) {
            addCriterion("isv_no >", value, "isvNo");
            return (Criteria) this;
        }

        public Criteria andIsvNoGreaterThanOrEqualTo(String value) {
            addCriterion("isv_no >=", value, "isvNo");
            return (Criteria) this;
        }

        public Criteria andIsvNoLessThan(String value) {
            addCriterion("isv_no <", value, "isvNo");
            return (Criteria) this;
        }

        public Criteria andIsvNoLessThanOrEqualTo(String value) {
            addCriterion("isv_no <=", value, "isvNo");
            return (Criteria) this;
        }

        public Criteria andIsvNoLike(String value) {
            addCriterion("isv_no like", value, "isvNo");
            return (Criteria) this;
        }

        public Criteria andIsvNoNotLike(String value) {
            addCriterion("isv_no not like", value, "isvNo");
            return (Criteria) this;
        }

        public Criteria andIsvNoIn(List<String> values) {
            addCriterion("isv_no in", values, "isvNo");
            return (Criteria) this;
        }

        public Criteria andIsvNoNotIn(List<String> values) {
            addCriterion("isv_no not in", values, "isvNo");
            return (Criteria) this;
        }

        public Criteria andIsvNoBetween(String value1, String value2) {
            addCriterion("isv_no between", value1, value2, "isvNo");
            return (Criteria) this;
        }

        public Criteria andIsvNoNotBetween(String value1, String value2) {
            addCriterion("isv_no not between", value1, value2, "isvNo");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNull() {
            addCriterion("app_id is null");
            return (Criteria) this;
        }

        public Criteria andAppIdIsNotNull() {
            addCriterion("app_id is not null");
            return (Criteria) this;
        }

        public Criteria andAppIdEqualTo(String value) {
            addCriterion("app_id =", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotEqualTo(String value) {
            addCriterion("app_id <>", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThan(String value) {
            addCriterion("app_id >", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdGreaterThanOrEqualTo(String value) {
            addCriterion("app_id >=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThan(String value) {
            addCriterion("app_id <", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLessThanOrEqualTo(String value) {
            addCriterion("app_id <=", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdLike(String value) {
            addCriterion("app_id like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotLike(String value) {
            addCriterion("app_id not like", value, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdIn(List<String> values) {
            addCriterion("app_id in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotIn(List<String> values) {
            addCriterion("app_id not in", values, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdBetween(String value1, String value2) {
            addCriterion("app_id between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andAppIdNotBetween(String value1, String value2) {
            addCriterion("app_id not between", value1, value2, "appId");
            return (Criteria) this;
        }

        public Criteria andMchNameIsNull() {
            addCriterion("mch_name is null");
            return (Criteria) this;
        }

        public Criteria andMchNameIsNotNull() {
            addCriterion("mch_name is not null");
            return (Criteria) this;
        }

        public Criteria andMchNameEqualTo(String value) {
            addCriterion("mch_name =", value, "mchName");
            return (Criteria) this;
        }

        public Criteria andMchNameNotEqualTo(String value) {
            addCriterion("mch_name <>", value, "mchName");
            return (Criteria) this;
        }

        public Criteria andMchNameGreaterThan(String value) {
            addCriterion("mch_name >", value, "mchName");
            return (Criteria) this;
        }

        public Criteria andMchNameGreaterThanOrEqualTo(String value) {
            addCriterion("mch_name >=", value, "mchName");
            return (Criteria) this;
        }

        public Criteria andMchNameLessThan(String value) {
            addCriterion("mch_name <", value, "mchName");
            return (Criteria) this;
        }

        public Criteria andMchNameLessThanOrEqualTo(String value) {
            addCriterion("mch_name <=", value, "mchName");
            return (Criteria) this;
        }

        public Criteria andMchNameLike(String value) {
            addCriterion("mch_name like", value, "mchName");
            return (Criteria) this;
        }

        public Criteria andMchNameNotLike(String value) {
            addCriterion("mch_name not like", value, "mchName");
            return (Criteria) this;
        }

        public Criteria andMchNameIn(List<String> values) {
            addCriterion("mch_name in", values, "mchName");
            return (Criteria) this;
        }

        public Criteria andMchNameNotIn(List<String> values) {
            addCriterion("mch_name not in", values, "mchName");
            return (Criteria) this;
        }

        public Criteria andMchNameBetween(String value1, String value2) {
            addCriterion("mch_name between", value1, value2, "mchName");
            return (Criteria) this;
        }

        public Criteria andMchNameNotBetween(String value1, String value2) {
            addCriterion("mch_name not between", value1, value2, "mchName");
            return (Criteria) this;
        }

        public Criteria andMchTypeIsNull() {
            addCriterion("mch_type is null");
            return (Criteria) this;
        }

        public Criteria andMchTypeIsNotNull() {
            addCriterion("mch_type is not null");
            return (Criteria) this;
        }

        public Criteria andMchTypeEqualTo(Byte value) {
            addCriterion("mch_type =", value, "mchType");
            return (Criteria) this;
        }

        public Criteria andMchTypeNotEqualTo(Byte value) {
            addCriterion("mch_type <>", value, "mchType");
            return (Criteria) this;
        }

        public Criteria andMchTypeGreaterThan(Byte value) {
            addCriterion("mch_type >", value, "mchType");
            return (Criteria) this;
        }

        public Criteria andMchTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("mch_type >=", value, "mchType");
            return (Criteria) this;
        }

        public Criteria andMchTypeLessThan(Byte value) {
            addCriterion("mch_type <", value, "mchType");
            return (Criteria) this;
        }

        public Criteria andMchTypeLessThanOrEqualTo(Byte value) {
            addCriterion("mch_type <=", value, "mchType");
            return (Criteria) this;
        }

        public Criteria andMchTypeIn(List<Byte> values) {
            addCriterion("mch_type in", values, "mchType");
            return (Criteria) this;
        }

        public Criteria andMchTypeNotIn(List<Byte> values) {
            addCriterion("mch_type not in", values, "mchType");
            return (Criteria) this;
        }

        public Criteria andMchTypeBetween(Byte value1, Byte value2) {
            addCriterion("mch_type between", value1, value2, "mchType");
            return (Criteria) this;
        }

        public Criteria andMchTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("mch_type not between", value1, value2, "mchType");
            return (Criteria) this;
        }

        public Criteria andMchOrderNoIsNull() {
            addCriterion("mch_order_no is null");
            return (Criteria) this;
        }

        public Criteria andMchOrderNoIsNotNull() {
            addCriterion("mch_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andMchOrderNoEqualTo(String value) {
            addCriterion("mch_order_no =", value, "mchOrderNo");
            return (Criteria) this;
        }

        public Criteria andMchOrderNoNotEqualTo(String value) {
            addCriterion("mch_order_no <>", value, "mchOrderNo");
            return (Criteria) this;
        }

        public Criteria andMchOrderNoGreaterThan(String value) {
            addCriterion("mch_order_no >", value, "mchOrderNo");
            return (Criteria) this;
        }

        public Criteria andMchOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("mch_order_no >=", value, "mchOrderNo");
            return (Criteria) this;
        }

        public Criteria andMchOrderNoLessThan(String value) {
            addCriterion("mch_order_no <", value, "mchOrderNo");
            return (Criteria) this;
        }

        public Criteria andMchOrderNoLessThanOrEqualTo(String value) {
            addCriterion("mch_order_no <=", value, "mchOrderNo");
            return (Criteria) this;
        }

        public Criteria andMchOrderNoLike(String value) {
            addCriterion("mch_order_no like", value, "mchOrderNo");
            return (Criteria) this;
        }

        public Criteria andMchOrderNoNotLike(String value) {
            addCriterion("mch_order_no not like", value, "mchOrderNo");
            return (Criteria) this;
        }

        public Criteria andMchOrderNoIn(List<String> values) {
            addCriterion("mch_order_no in", values, "mchOrderNo");
            return (Criteria) this;
        }

        public Criteria andMchOrderNoNotIn(List<String> values) {
            addCriterion("mch_order_no not in", values, "mchOrderNo");
            return (Criteria) this;
        }

        public Criteria andMchOrderNoBetween(String value1, String value2) {
            addCriterion("mch_order_no between", value1, value2, "mchOrderNo");
            return (Criteria) this;
        }

        public Criteria andMchOrderNoNotBetween(String value1, String value2) {
            addCriterion("mch_order_no not between", value1, value2, "mchOrderNo");
            return (Criteria) this;
        }

        public Criteria andIfCodeIsNull() {
            addCriterion("if_code is null");
            return (Criteria) this;
        }

        public Criteria andIfCodeIsNotNull() {
            addCriterion("if_code is not null");
            return (Criteria) this;
        }

        public Criteria andIfCodeEqualTo(String value) {
            addCriterion("if_code =", value, "ifCode");
            return (Criteria) this;
        }

        public Criteria andIfCodeNotEqualTo(String value) {
            addCriterion("if_code <>", value, "ifCode");
            return (Criteria) this;
        }

        public Criteria andIfCodeGreaterThan(String value) {
            addCriterion("if_code >", value, "ifCode");
            return (Criteria) this;
        }

        public Criteria andIfCodeGreaterThanOrEqualTo(String value) {
            addCriterion("if_code >=", value, "ifCode");
            return (Criteria) this;
        }

        public Criteria andIfCodeLessThan(String value) {
            addCriterion("if_code <", value, "ifCode");
            return (Criteria) this;
        }

        public Criteria andIfCodeLessThanOrEqualTo(String value) {
            addCriterion("if_code <=", value, "ifCode");
            return (Criteria) this;
        }

        public Criteria andIfCodeLike(String value) {
            addCriterion("if_code like", value, "ifCode");
            return (Criteria) this;
        }

        public Criteria andIfCodeNotLike(String value) {
            addCriterion("if_code not like", value, "ifCode");
            return (Criteria) this;
        }

        public Criteria andIfCodeIn(List<String> values) {
            addCriterion("if_code in", values, "ifCode");
            return (Criteria) this;
        }

        public Criteria andIfCodeNotIn(List<String> values) {
            addCriterion("if_code not in", values, "ifCode");
            return (Criteria) this;
        }

        public Criteria andIfCodeBetween(String value1, String value2) {
            addCriterion("if_code between", value1, value2, "ifCode");
            return (Criteria) this;
        }

        public Criteria andIfCodeNotBetween(String value1, String value2) {
            addCriterion("if_code not between", value1, value2, "ifCode");
            return (Criteria) this;
        }

        public Criteria andWayCodeIsNull() {
            addCriterion("way_code is null");
            return (Criteria) this;
        }

        public Criteria andWayCodeIsNotNull() {
            addCriterion("way_code is not null");
            return (Criteria) this;
        }

        public Criteria andWayCodeEqualTo(String value) {
            addCriterion("way_code =", value, "wayCode");
            return (Criteria) this;
        }

        public Criteria andWayCodeNotEqualTo(String value) {
            addCriterion("way_code <>", value, "wayCode");
            return (Criteria) this;
        }

        public Criteria andWayCodeGreaterThan(String value) {
            addCriterion("way_code >", value, "wayCode");
            return (Criteria) this;
        }

        public Criteria andWayCodeGreaterThanOrEqualTo(String value) {
            addCriterion("way_code >=", value, "wayCode");
            return (Criteria) this;
        }

        public Criteria andWayCodeLessThan(String value) {
            addCriterion("way_code <", value, "wayCode");
            return (Criteria) this;
        }

        public Criteria andWayCodeLessThanOrEqualTo(String value) {
            addCriterion("way_code <=", value, "wayCode");
            return (Criteria) this;
        }

        public Criteria andWayCodeLike(String value) {
            addCriterion("way_code like", value, "wayCode");
            return (Criteria) this;
        }

        public Criteria andWayCodeNotLike(String value) {
            addCriterion("way_code not like", value, "wayCode");
            return (Criteria) this;
        }

        public Criteria andWayCodeIn(List<String> values) {
            addCriterion("way_code in", values, "wayCode");
            return (Criteria) this;
        }

        public Criteria andWayCodeNotIn(List<String> values) {
            addCriterion("way_code not in", values, "wayCode");
            return (Criteria) this;
        }

        public Criteria andWayCodeBetween(String value1, String value2) {
            addCriterion("way_code between", value1, value2, "wayCode");
            return (Criteria) this;
        }

        public Criteria andWayCodeNotBetween(String value1, String value2) {
            addCriterion("way_code not between", value1, value2, "wayCode");
            return (Criteria) this;
        }

        public Criteria andAmountIsNull() {
            addCriterion("amount is null");
            return (Criteria) this;
        }

        public Criteria andAmountIsNotNull() {
            addCriterion("amount is not null");
            return (Criteria) this;
        }

        public Criteria andAmountEqualTo(Long value) {
            addCriterion("amount =", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotEqualTo(Long value) {
            addCriterion("amount <>", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThan(Long value) {
            addCriterion("amount >", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("amount >=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThan(Long value) {
            addCriterion("amount <", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountLessThanOrEqualTo(Long value) {
            addCriterion("amount <=", value, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountIn(List<Long> values) {
            addCriterion("amount in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotIn(List<Long> values) {
            addCriterion("amount not in", values, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountBetween(Long value1, Long value2) {
            addCriterion("amount between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andAmountNotBetween(Long value1, Long value2) {
            addCriterion("amount not between", value1, value2, "amount");
            return (Criteria) this;
        }

        public Criteria andMchFeeRateIsNull() {
            addCriterion("mch_fee_rate is null");
            return (Criteria) this;
        }

        public Criteria andMchFeeRateIsNotNull() {
            addCriterion("mch_fee_rate is not null");
            return (Criteria) this;
        }

        public Criteria andMchFeeRateEqualTo(BigDecimal value) {
            addCriterion("mch_fee_rate =", value, "mchFeeRate");
            return (Criteria) this;
        }

        public Criteria andMchFeeRateNotEqualTo(BigDecimal value) {
            addCriterion("mch_fee_rate <>", value, "mchFeeRate");
            return (Criteria) this;
        }

        public Criteria andMchFeeRateGreaterThan(BigDecimal value) {
            addCriterion("mch_fee_rate >", value, "mchFeeRate");
            return (Criteria) this;
        }

        public Criteria andMchFeeRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("mch_fee_rate >=", value, "mchFeeRate");
            return (Criteria) this;
        }

        public Criteria andMchFeeRateLessThan(BigDecimal value) {
            addCriterion("mch_fee_rate <", value, "mchFeeRate");
            return (Criteria) this;
        }

        public Criteria andMchFeeRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("mch_fee_rate <=", value, "mchFeeRate");
            return (Criteria) this;
        }

        public Criteria andMchFeeRateIn(List<BigDecimal> values) {
            addCriterion("mch_fee_rate in", values, "mchFeeRate");
            return (Criteria) this;
        }

        public Criteria andMchFeeRateNotIn(List<BigDecimal> values) {
            addCriterion("mch_fee_rate not in", values, "mchFeeRate");
            return (Criteria) this;
        }

        public Criteria andMchFeeRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mch_fee_rate between", value1, value2, "mchFeeRate");
            return (Criteria) this;
        }

        public Criteria andMchFeeRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("mch_fee_rate not between", value1, value2, "mchFeeRate");
            return (Criteria) this;
        }

        public Criteria andMchFeeAmountIsNull() {
            addCriterion("mch_fee_amount is null");
            return (Criteria) this;
        }

        public Criteria andMchFeeAmountIsNotNull() {
            addCriterion("mch_fee_amount is not null");
            return (Criteria) this;
        }

        public Criteria andMchFeeAmountEqualTo(Long value) {
            addCriterion("mch_fee_amount =", value, "mchFeeAmount");
            return (Criteria) this;
        }

        public Criteria andMchFeeAmountNotEqualTo(Long value) {
            addCriterion("mch_fee_amount <>", value, "mchFeeAmount");
            return (Criteria) this;
        }

        public Criteria andMchFeeAmountGreaterThan(Long value) {
            addCriterion("mch_fee_amount >", value, "mchFeeAmount");
            return (Criteria) this;
        }

        public Criteria andMchFeeAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("mch_fee_amount >=", value, "mchFeeAmount");
            return (Criteria) this;
        }

        public Criteria andMchFeeAmountLessThan(Long value) {
            addCriterion("mch_fee_amount <", value, "mchFeeAmount");
            return (Criteria) this;
        }

        public Criteria andMchFeeAmountLessThanOrEqualTo(Long value) {
            addCriterion("mch_fee_amount <=", value, "mchFeeAmount");
            return (Criteria) this;
        }

        public Criteria andMchFeeAmountIn(List<Long> values) {
            addCriterion("mch_fee_amount in", values, "mchFeeAmount");
            return (Criteria) this;
        }

        public Criteria andMchFeeAmountNotIn(List<Long> values) {
            addCriterion("mch_fee_amount not in", values, "mchFeeAmount");
            return (Criteria) this;
        }

        public Criteria andMchFeeAmountBetween(Long value1, Long value2) {
            addCriterion("mch_fee_amount between", value1, value2, "mchFeeAmount");
            return (Criteria) this;
        }

        public Criteria andMchFeeAmountNotBetween(Long value1, Long value2) {
            addCriterion("mch_fee_amount not between", value1, value2, "mchFeeAmount");
            return (Criteria) this;
        }

        public Criteria andCurrencyIsNull() {
            addCriterion("currency is null");
            return (Criteria) this;
        }

        public Criteria andCurrencyIsNotNull() {
            addCriterion("currency is not null");
            return (Criteria) this;
        }

        public Criteria andCurrencyEqualTo(String value) {
            addCriterion("currency =", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotEqualTo(String value) {
            addCriterion("currency <>", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyGreaterThan(String value) {
            addCriterion("currency >", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("currency >=", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLessThan(String value) {
            addCriterion("currency <", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLessThanOrEqualTo(String value) {
            addCriterion("currency <=", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyLike(String value) {
            addCriterion("currency like", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotLike(String value) {
            addCriterion("currency not like", value, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyIn(List<String> values) {
            addCriterion("currency in", values, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotIn(List<String> values) {
            addCriterion("currency not in", values, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyBetween(String value1, String value2) {
            addCriterion("currency between", value1, value2, "currency");
            return (Criteria) this;
        }

        public Criteria andCurrencyNotBetween(String value1, String value2) {
            addCriterion("currency not between", value1, value2, "currency");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Byte value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Byte value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Byte value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Byte value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Byte value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Byte> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Byte> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Byte value1, Byte value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Byte value1, Byte value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andNotifyStateIsNull() {
            addCriterion("notify_state is null");
            return (Criteria) this;
        }

        public Criteria andNotifyStateIsNotNull() {
            addCriterion("notify_state is not null");
            return (Criteria) this;
        }

        public Criteria andNotifyStateEqualTo(Byte value) {
            addCriterion("notify_state =", value, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateNotEqualTo(Byte value) {
            addCriterion("notify_state <>", value, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateGreaterThan(Byte value) {
            addCriterion("notify_state >", value, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("notify_state >=", value, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateLessThan(Byte value) {
            addCriterion("notify_state <", value, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateLessThanOrEqualTo(Byte value) {
            addCriterion("notify_state <=", value, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateIn(List<Byte> values) {
            addCriterion("notify_state in", values, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateNotIn(List<Byte> values) {
            addCriterion("notify_state not in", values, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateBetween(Byte value1, Byte value2) {
            addCriterion("notify_state between", value1, value2, "notifyState");
            return (Criteria) this;
        }

        public Criteria andNotifyStateNotBetween(Byte value1, Byte value2) {
            addCriterion("notify_state not between", value1, value2, "notifyState");
            return (Criteria) this;
        }

        public Criteria andClientIpIsNull() {
            addCriterion("client_ip is null");
            return (Criteria) this;
        }

        public Criteria andClientIpIsNotNull() {
            addCriterion("client_ip is not null");
            return (Criteria) this;
        }

        public Criteria andClientIpEqualTo(String value) {
            addCriterion("client_ip =", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpNotEqualTo(String value) {
            addCriterion("client_ip <>", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpGreaterThan(String value) {
            addCriterion("client_ip >", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpGreaterThanOrEqualTo(String value) {
            addCriterion("client_ip >=", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpLessThan(String value) {
            addCriterion("client_ip <", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpLessThanOrEqualTo(String value) {
            addCriterion("client_ip <=", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpLike(String value) {
            addCriterion("client_ip like", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpNotLike(String value) {
            addCriterion("client_ip not like", value, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpIn(List<String> values) {
            addCriterion("client_ip in", values, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpNotIn(List<String> values) {
            addCriterion("client_ip not in", values, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpBetween(String value1, String value2) {
            addCriterion("client_ip between", value1, value2, "clientIp");
            return (Criteria) this;
        }

        public Criteria andClientIpNotBetween(String value1, String value2) {
            addCriterion("client_ip not between", value1, value2, "clientIp");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNull() {
            addCriterion("subject is null");
            return (Criteria) this;
        }

        public Criteria andSubjectIsNotNull() {
            addCriterion("subject is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectEqualTo(String value) {
            addCriterion("subject =", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotEqualTo(String value) {
            addCriterion("subject <>", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThan(String value) {
            addCriterion("subject >", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectGreaterThanOrEqualTo(String value) {
            addCriterion("subject >=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThan(String value) {
            addCriterion("subject <", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLessThanOrEqualTo(String value) {
            addCriterion("subject <=", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectLike(String value) {
            addCriterion("subject like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotLike(String value) {
            addCriterion("subject not like", value, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectIn(List<String> values) {
            addCriterion("subject in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotIn(List<String> values) {
            addCriterion("subject not in", values, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectBetween(String value1, String value2) {
            addCriterion("subject between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andSubjectNotBetween(String value1, String value2) {
            addCriterion("subject not between", value1, value2, "subject");
            return (Criteria) this;
        }

        public Criteria andBodyIsNull() {
            addCriterion("body is null");
            return (Criteria) this;
        }

        public Criteria andBodyIsNotNull() {
            addCriterion("body is not null");
            return (Criteria) this;
        }

        public Criteria andBodyEqualTo(String value) {
            addCriterion("body =", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotEqualTo(String value) {
            addCriterion("body <>", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyGreaterThan(String value) {
            addCriterion("body >", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyGreaterThanOrEqualTo(String value) {
            addCriterion("body >=", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLessThan(String value) {
            addCriterion("body <", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLessThanOrEqualTo(String value) {
            addCriterion("body <=", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyLike(String value) {
            addCriterion("body like", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotLike(String value) {
            addCriterion("body not like", value, "body");
            return (Criteria) this;
        }

        public Criteria andBodyIn(List<String> values) {
            addCriterion("body in", values, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotIn(List<String> values) {
            addCriterion("body not in", values, "body");
            return (Criteria) this;
        }

        public Criteria andBodyBetween(String value1, String value2) {
            addCriterion("body between", value1, value2, "body");
            return (Criteria) this;
        }

        public Criteria andBodyNotBetween(String value1, String value2) {
            addCriterion("body not between", value1, value2, "body");
            return (Criteria) this;
        }

        public Criteria andChannelExtraIsNull() {
            addCriterion("channel_extra is null");
            return (Criteria) this;
        }

        public Criteria andChannelExtraIsNotNull() {
            addCriterion("channel_extra is not null");
            return (Criteria) this;
        }

        public Criteria andChannelExtraEqualTo(String value) {
            addCriterion("channel_extra =", value, "channelExtra");
            return (Criteria) this;
        }

        public Criteria andChannelExtraNotEqualTo(String value) {
            addCriterion("channel_extra <>", value, "channelExtra");
            return (Criteria) this;
        }

        public Criteria andChannelExtraGreaterThan(String value) {
            addCriterion("channel_extra >", value, "channelExtra");
            return (Criteria) this;
        }

        public Criteria andChannelExtraGreaterThanOrEqualTo(String value) {
            addCriterion("channel_extra >=", value, "channelExtra");
            return (Criteria) this;
        }

        public Criteria andChannelExtraLessThan(String value) {
            addCriterion("channel_extra <", value, "channelExtra");
            return (Criteria) this;
        }

        public Criteria andChannelExtraLessThanOrEqualTo(String value) {
            addCriterion("channel_extra <=", value, "channelExtra");
            return (Criteria) this;
        }

        public Criteria andChannelExtraLike(String value) {
            addCriterion("channel_extra like", value, "channelExtra");
            return (Criteria) this;
        }

        public Criteria andChannelExtraNotLike(String value) {
            addCriterion("channel_extra not like", value, "channelExtra");
            return (Criteria) this;
        }

        public Criteria andChannelExtraIn(List<String> values) {
            addCriterion("channel_extra in", values, "channelExtra");
            return (Criteria) this;
        }

        public Criteria andChannelExtraNotIn(List<String> values) {
            addCriterion("channel_extra not in", values, "channelExtra");
            return (Criteria) this;
        }

        public Criteria andChannelExtraBetween(String value1, String value2) {
            addCriterion("channel_extra between", value1, value2, "channelExtra");
            return (Criteria) this;
        }

        public Criteria andChannelExtraNotBetween(String value1, String value2) {
            addCriterion("channel_extra not between", value1, value2, "channelExtra");
            return (Criteria) this;
        }

        public Criteria andChannelUserIsNull() {
            addCriterion("channel_user is null");
            return (Criteria) this;
        }

        public Criteria andChannelUserIsNotNull() {
            addCriterion("channel_user is not null");
            return (Criteria) this;
        }

        public Criteria andChannelUserEqualTo(String value) {
            addCriterion("channel_user =", value, "channelUser");
            return (Criteria) this;
        }

        public Criteria andChannelUserNotEqualTo(String value) {
            addCriterion("channel_user <>", value, "channelUser");
            return (Criteria) this;
        }

        public Criteria andChannelUserGreaterThan(String value) {
            addCriterion("channel_user >", value, "channelUser");
            return (Criteria) this;
        }

        public Criteria andChannelUserGreaterThanOrEqualTo(String value) {
            addCriterion("channel_user >=", value, "channelUser");
            return (Criteria) this;
        }

        public Criteria andChannelUserLessThan(String value) {
            addCriterion("channel_user <", value, "channelUser");
            return (Criteria) this;
        }

        public Criteria andChannelUserLessThanOrEqualTo(String value) {
            addCriterion("channel_user <=", value, "channelUser");
            return (Criteria) this;
        }

        public Criteria andChannelUserLike(String value) {
            addCriterion("channel_user like", value, "channelUser");
            return (Criteria) this;
        }

        public Criteria andChannelUserNotLike(String value) {
            addCriterion("channel_user not like", value, "channelUser");
            return (Criteria) this;
        }

        public Criteria andChannelUserIn(List<String> values) {
            addCriterion("channel_user in", values, "channelUser");
            return (Criteria) this;
        }

        public Criteria andChannelUserNotIn(List<String> values) {
            addCriterion("channel_user not in", values, "channelUser");
            return (Criteria) this;
        }

        public Criteria andChannelUserBetween(String value1, String value2) {
            addCriterion("channel_user between", value1, value2, "channelUser");
            return (Criteria) this;
        }

        public Criteria andChannelUserNotBetween(String value1, String value2) {
            addCriterion("channel_user not between", value1, value2, "channelUser");
            return (Criteria) this;
        }

        public Criteria andChannelOrderNoIsNull() {
            addCriterion("channel_order_no is null");
            return (Criteria) this;
        }

        public Criteria andChannelOrderNoIsNotNull() {
            addCriterion("channel_order_no is not null");
            return (Criteria) this;
        }

        public Criteria andChannelOrderNoEqualTo(String value) {
            addCriterion("channel_order_no =", value, "channelOrderNo");
            return (Criteria) this;
        }

        public Criteria andChannelOrderNoNotEqualTo(String value) {
            addCriterion("channel_order_no <>", value, "channelOrderNo");
            return (Criteria) this;
        }

        public Criteria andChannelOrderNoGreaterThan(String value) {
            addCriterion("channel_order_no >", value, "channelOrderNo");
            return (Criteria) this;
        }

        public Criteria andChannelOrderNoGreaterThanOrEqualTo(String value) {
            addCriterion("channel_order_no >=", value, "channelOrderNo");
            return (Criteria) this;
        }

        public Criteria andChannelOrderNoLessThan(String value) {
            addCriterion("channel_order_no <", value, "channelOrderNo");
            return (Criteria) this;
        }

        public Criteria andChannelOrderNoLessThanOrEqualTo(String value) {
            addCriterion("channel_order_no <=", value, "channelOrderNo");
            return (Criteria) this;
        }

        public Criteria andChannelOrderNoLike(String value) {
            addCriterion("channel_order_no like", value, "channelOrderNo");
            return (Criteria) this;
        }

        public Criteria andChannelOrderNoNotLike(String value) {
            addCriterion("channel_order_no not like", value, "channelOrderNo");
            return (Criteria) this;
        }

        public Criteria andChannelOrderNoIn(List<String> values) {
            addCriterion("channel_order_no in", values, "channelOrderNo");
            return (Criteria) this;
        }

        public Criteria andChannelOrderNoNotIn(List<String> values) {
            addCriterion("channel_order_no not in", values, "channelOrderNo");
            return (Criteria) this;
        }

        public Criteria andChannelOrderNoBetween(String value1, String value2) {
            addCriterion("channel_order_no between", value1, value2, "channelOrderNo");
            return (Criteria) this;
        }

        public Criteria andChannelOrderNoNotBetween(String value1, String value2) {
            addCriterion("channel_order_no not between", value1, value2, "channelOrderNo");
            return (Criteria) this;
        }

        public Criteria andRefundStateIsNull() {
            addCriterion("refund_state is null");
            return (Criteria) this;
        }

        public Criteria andRefundStateIsNotNull() {
            addCriterion("refund_state is not null");
            return (Criteria) this;
        }

        public Criteria andRefundStateEqualTo(Byte value) {
            addCriterion("refund_state =", value, "refundState");
            return (Criteria) this;
        }

        public Criteria andRefundStateNotEqualTo(Byte value) {
            addCriterion("refund_state <>", value, "refundState");
            return (Criteria) this;
        }

        public Criteria andRefundStateGreaterThan(Byte value) {
            addCriterion("refund_state >", value, "refundState");
            return (Criteria) this;
        }

        public Criteria andRefundStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("refund_state >=", value, "refundState");
            return (Criteria) this;
        }

        public Criteria andRefundStateLessThan(Byte value) {
            addCriterion("refund_state <", value, "refundState");
            return (Criteria) this;
        }

        public Criteria andRefundStateLessThanOrEqualTo(Byte value) {
            addCriterion("refund_state <=", value, "refundState");
            return (Criteria) this;
        }

        public Criteria andRefundStateIn(List<Byte> values) {
            addCriterion("refund_state in", values, "refundState");
            return (Criteria) this;
        }

        public Criteria andRefundStateNotIn(List<Byte> values) {
            addCriterion("refund_state not in", values, "refundState");
            return (Criteria) this;
        }

        public Criteria andRefundStateBetween(Byte value1, Byte value2) {
            addCriterion("refund_state between", value1, value2, "refundState");
            return (Criteria) this;
        }

        public Criteria andRefundStateNotBetween(Byte value1, Byte value2) {
            addCriterion("refund_state not between", value1, value2, "refundState");
            return (Criteria) this;
        }

        public Criteria andRefundTimesIsNull() {
            addCriterion("refund_times is null");
            return (Criteria) this;
        }

        public Criteria andRefundTimesIsNotNull() {
            addCriterion("refund_times is not null");
            return (Criteria) this;
        }

        public Criteria andRefundTimesEqualTo(Integer value) {
            addCriterion("refund_times =", value, "refundTimes");
            return (Criteria) this;
        }

        public Criteria andRefundTimesNotEqualTo(Integer value) {
            addCriterion("refund_times <>", value, "refundTimes");
            return (Criteria) this;
        }

        public Criteria andRefundTimesGreaterThan(Integer value) {
            addCriterion("refund_times >", value, "refundTimes");
            return (Criteria) this;
        }

        public Criteria andRefundTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("refund_times >=", value, "refundTimes");
            return (Criteria) this;
        }

        public Criteria andRefundTimesLessThan(Integer value) {
            addCriterion("refund_times <", value, "refundTimes");
            return (Criteria) this;
        }

        public Criteria andRefundTimesLessThanOrEqualTo(Integer value) {
            addCriterion("refund_times <=", value, "refundTimes");
            return (Criteria) this;
        }

        public Criteria andRefundTimesIn(List<Integer> values) {
            addCriterion("refund_times in", values, "refundTimes");
            return (Criteria) this;
        }

        public Criteria andRefundTimesNotIn(List<Integer> values) {
            addCriterion("refund_times not in", values, "refundTimes");
            return (Criteria) this;
        }

        public Criteria andRefundTimesBetween(Integer value1, Integer value2) {
            addCriterion("refund_times between", value1, value2, "refundTimes");
            return (Criteria) this;
        }

        public Criteria andRefundTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("refund_times not between", value1, value2, "refundTimes");
            return (Criteria) this;
        }

        public Criteria andRefundAmountIsNull() {
            addCriterion("refund_amount is null");
            return (Criteria) this;
        }

        public Criteria andRefundAmountIsNotNull() {
            addCriterion("refund_amount is not null");
            return (Criteria) this;
        }

        public Criteria andRefundAmountEqualTo(Long value) {
            addCriterion("refund_amount =", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountNotEqualTo(Long value) {
            addCriterion("refund_amount <>", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountGreaterThan(Long value) {
            addCriterion("refund_amount >", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountGreaterThanOrEqualTo(Long value) {
            addCriterion("refund_amount >=", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountLessThan(Long value) {
            addCriterion("refund_amount <", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountLessThanOrEqualTo(Long value) {
            addCriterion("refund_amount <=", value, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountIn(List<Long> values) {
            addCriterion("refund_amount in", values, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountNotIn(List<Long> values) {
            addCriterion("refund_amount not in", values, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountBetween(Long value1, Long value2) {
            addCriterion("refund_amount between", value1, value2, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andRefundAmountNotBetween(Long value1, Long value2) {
            addCriterion("refund_amount not between", value1, value2, "refundAmount");
            return (Criteria) this;
        }

        public Criteria andDivisionModeIsNull() {
            addCriterion("division_mode is null");
            return (Criteria) this;
        }

        public Criteria andDivisionModeIsNotNull() {
            addCriterion("division_mode is not null");
            return (Criteria) this;
        }

        public Criteria andDivisionModeEqualTo(Byte value) {
            addCriterion("division_mode =", value, "divisionMode");
            return (Criteria) this;
        }

        public Criteria andDivisionModeNotEqualTo(Byte value) {
            addCriterion("division_mode <>", value, "divisionMode");
            return (Criteria) this;
        }

        public Criteria andDivisionModeGreaterThan(Byte value) {
            addCriterion("division_mode >", value, "divisionMode");
            return (Criteria) this;
        }

        public Criteria andDivisionModeGreaterThanOrEqualTo(Byte value) {
            addCriterion("division_mode >=", value, "divisionMode");
            return (Criteria) this;
        }

        public Criteria andDivisionModeLessThan(Byte value) {
            addCriterion("division_mode <", value, "divisionMode");
            return (Criteria) this;
        }

        public Criteria andDivisionModeLessThanOrEqualTo(Byte value) {
            addCriterion("division_mode <=", value, "divisionMode");
            return (Criteria) this;
        }

        public Criteria andDivisionModeIn(List<Byte> values) {
            addCriterion("division_mode in", values, "divisionMode");
            return (Criteria) this;
        }

        public Criteria andDivisionModeNotIn(List<Byte> values) {
            addCriterion("division_mode not in", values, "divisionMode");
            return (Criteria) this;
        }

        public Criteria andDivisionModeBetween(Byte value1, Byte value2) {
            addCriterion("division_mode between", value1, value2, "divisionMode");
            return (Criteria) this;
        }

        public Criteria andDivisionModeNotBetween(Byte value1, Byte value2) {
            addCriterion("division_mode not between", value1, value2, "divisionMode");
            return (Criteria) this;
        }

        public Criteria andDivisionStateIsNull() {
            addCriterion("division_state is null");
            return (Criteria) this;
        }

        public Criteria andDivisionStateIsNotNull() {
            addCriterion("division_state is not null");
            return (Criteria) this;
        }

        public Criteria andDivisionStateEqualTo(Byte value) {
            addCriterion("division_state =", value, "divisionState");
            return (Criteria) this;
        }

        public Criteria andDivisionStateNotEqualTo(Byte value) {
            addCriterion("division_state <>", value, "divisionState");
            return (Criteria) this;
        }

        public Criteria andDivisionStateGreaterThan(Byte value) {
            addCriterion("division_state >", value, "divisionState");
            return (Criteria) this;
        }

        public Criteria andDivisionStateGreaterThanOrEqualTo(Byte value) {
            addCriterion("division_state >=", value, "divisionState");
            return (Criteria) this;
        }

        public Criteria andDivisionStateLessThan(Byte value) {
            addCriterion("division_state <", value, "divisionState");
            return (Criteria) this;
        }

        public Criteria andDivisionStateLessThanOrEqualTo(Byte value) {
            addCriterion("division_state <=", value, "divisionState");
            return (Criteria) this;
        }

        public Criteria andDivisionStateIn(List<Byte> values) {
            addCriterion("division_state in", values, "divisionState");
            return (Criteria) this;
        }

        public Criteria andDivisionStateNotIn(List<Byte> values) {
            addCriterion("division_state not in", values, "divisionState");
            return (Criteria) this;
        }

        public Criteria andDivisionStateBetween(Byte value1, Byte value2) {
            addCriterion("division_state between", value1, value2, "divisionState");
            return (Criteria) this;
        }

        public Criteria andDivisionStateNotBetween(Byte value1, Byte value2) {
            addCriterion("division_state not between", value1, value2, "divisionState");
            return (Criteria) this;
        }

        public Criteria andDivisionLastTimeIsNull() {
            addCriterion("division_last_time is null");
            return (Criteria) this;
        }

        public Criteria andDivisionLastTimeIsNotNull() {
            addCriterion("division_last_time is not null");
            return (Criteria) this;
        }

        public Criteria andDivisionLastTimeEqualTo(Date value) {
            addCriterion("division_last_time =", value, "divisionLastTime");
            return (Criteria) this;
        }

        public Criteria andDivisionLastTimeNotEqualTo(Date value) {
            addCriterion("division_last_time <>", value, "divisionLastTime");
            return (Criteria) this;
        }

        public Criteria andDivisionLastTimeGreaterThan(Date value) {
            addCriterion("division_last_time >", value, "divisionLastTime");
            return (Criteria) this;
        }

        public Criteria andDivisionLastTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("division_last_time >=", value, "divisionLastTime");
            return (Criteria) this;
        }

        public Criteria andDivisionLastTimeLessThan(Date value) {
            addCriterion("division_last_time <", value, "divisionLastTime");
            return (Criteria) this;
        }

        public Criteria andDivisionLastTimeLessThanOrEqualTo(Date value) {
            addCriterion("division_last_time <=", value, "divisionLastTime");
            return (Criteria) this;
        }

        public Criteria andDivisionLastTimeIn(List<Date> values) {
            addCriterion("division_last_time in", values, "divisionLastTime");
            return (Criteria) this;
        }

        public Criteria andDivisionLastTimeNotIn(List<Date> values) {
            addCriterion("division_last_time not in", values, "divisionLastTime");
            return (Criteria) this;
        }

        public Criteria andDivisionLastTimeBetween(Date value1, Date value2) {
            addCriterion("division_last_time between", value1, value2, "divisionLastTime");
            return (Criteria) this;
        }

        public Criteria andDivisionLastTimeNotBetween(Date value1, Date value2) {
            addCriterion("division_last_time not between", value1, value2, "divisionLastTime");
            return (Criteria) this;
        }

        public Criteria andErrCodeIsNull() {
            addCriterion("err_code is null");
            return (Criteria) this;
        }

        public Criteria andErrCodeIsNotNull() {
            addCriterion("err_code is not null");
            return (Criteria) this;
        }

        public Criteria andErrCodeEqualTo(String value) {
            addCriterion("err_code =", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotEqualTo(String value) {
            addCriterion("err_code <>", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeGreaterThan(String value) {
            addCriterion("err_code >", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeGreaterThanOrEqualTo(String value) {
            addCriterion("err_code >=", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeLessThan(String value) {
            addCriterion("err_code <", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeLessThanOrEqualTo(String value) {
            addCriterion("err_code <=", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeLike(String value) {
            addCriterion("err_code like", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotLike(String value) {
            addCriterion("err_code not like", value, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeIn(List<String> values) {
            addCriterion("err_code in", values, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotIn(List<String> values) {
            addCriterion("err_code not in", values, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeBetween(String value1, String value2) {
            addCriterion("err_code between", value1, value2, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrCodeNotBetween(String value1, String value2) {
            addCriterion("err_code not between", value1, value2, "errCode");
            return (Criteria) this;
        }

        public Criteria andErrMsgIsNull() {
            addCriterion("err_msg is null");
            return (Criteria) this;
        }

        public Criteria andErrMsgIsNotNull() {
            addCriterion("err_msg is not null");
            return (Criteria) this;
        }

        public Criteria andErrMsgEqualTo(String value) {
            addCriterion("err_msg =", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgNotEqualTo(String value) {
            addCriterion("err_msg <>", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgGreaterThan(String value) {
            addCriterion("err_msg >", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgGreaterThanOrEqualTo(String value) {
            addCriterion("err_msg >=", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgLessThan(String value) {
            addCriterion("err_msg <", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgLessThanOrEqualTo(String value) {
            addCriterion("err_msg <=", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgLike(String value) {
            addCriterion("err_msg like", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgNotLike(String value) {
            addCriterion("err_msg not like", value, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgIn(List<String> values) {
            addCriterion("err_msg in", values, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgNotIn(List<String> values) {
            addCriterion("err_msg not in", values, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgBetween(String value1, String value2) {
            addCriterion("err_msg between", value1, value2, "errMsg");
            return (Criteria) this;
        }

        public Criteria andErrMsgNotBetween(String value1, String value2) {
            addCriterion("err_msg not between", value1, value2, "errMsg");
            return (Criteria) this;
        }

        public Criteria andExtParamIsNull() {
            addCriterion("ext_param is null");
            return (Criteria) this;
        }

        public Criteria andExtParamIsNotNull() {
            addCriterion("ext_param is not null");
            return (Criteria) this;
        }

        public Criteria andExtParamEqualTo(String value) {
            addCriterion("ext_param =", value, "extParam");
            return (Criteria) this;
        }

        public Criteria andExtParamNotEqualTo(String value) {
            addCriterion("ext_param <>", value, "extParam");
            return (Criteria) this;
        }

        public Criteria andExtParamGreaterThan(String value) {
            addCriterion("ext_param >", value, "extParam");
            return (Criteria) this;
        }

        public Criteria andExtParamGreaterThanOrEqualTo(String value) {
            addCriterion("ext_param >=", value, "extParam");
            return (Criteria) this;
        }

        public Criteria andExtParamLessThan(String value) {
            addCriterion("ext_param <", value, "extParam");
            return (Criteria) this;
        }

        public Criteria andExtParamLessThanOrEqualTo(String value) {
            addCriterion("ext_param <=", value, "extParam");
            return (Criteria) this;
        }

        public Criteria andExtParamLike(String value) {
            addCriterion("ext_param like", value, "extParam");
            return (Criteria) this;
        }

        public Criteria andExtParamNotLike(String value) {
            addCriterion("ext_param not like", value, "extParam");
            return (Criteria) this;
        }

        public Criteria andExtParamIn(List<String> values) {
            addCriterion("ext_param in", values, "extParam");
            return (Criteria) this;
        }

        public Criteria andExtParamNotIn(List<String> values) {
            addCriterion("ext_param not in", values, "extParam");
            return (Criteria) this;
        }

        public Criteria andExtParamBetween(String value1, String value2) {
            addCriterion("ext_param between", value1, value2, "extParam");
            return (Criteria) this;
        }

        public Criteria andExtParamNotBetween(String value1, String value2) {
            addCriterion("ext_param not between", value1, value2, "extParam");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlIsNull() {
            addCriterion("notify_url is null");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlIsNotNull() {
            addCriterion("notify_url is not null");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlEqualTo(String value) {
            addCriterion("notify_url =", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotEqualTo(String value) {
            addCriterion("notify_url <>", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlGreaterThan(String value) {
            addCriterion("notify_url >", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlGreaterThanOrEqualTo(String value) {
            addCriterion("notify_url >=", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlLessThan(String value) {
            addCriterion("notify_url <", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlLessThanOrEqualTo(String value) {
            addCriterion("notify_url <=", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlLike(String value) {
            addCriterion("notify_url like", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotLike(String value) {
            addCriterion("notify_url not like", value, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlIn(List<String> values) {
            addCriterion("notify_url in", values, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotIn(List<String> values) {
            addCriterion("notify_url not in", values, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlBetween(String value1, String value2) {
            addCriterion("notify_url between", value1, value2, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andNotifyUrlNotBetween(String value1, String value2) {
            addCriterion("notify_url not between", value1, value2, "notifyUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlIsNull() {
            addCriterion("return_url is null");
            return (Criteria) this;
        }

        public Criteria andReturnUrlIsNotNull() {
            addCriterion("return_url is not null");
            return (Criteria) this;
        }

        public Criteria andReturnUrlEqualTo(String value) {
            addCriterion("return_url =", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlNotEqualTo(String value) {
            addCriterion("return_url <>", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlGreaterThan(String value) {
            addCriterion("return_url >", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlGreaterThanOrEqualTo(String value) {
            addCriterion("return_url >=", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlLessThan(String value) {
            addCriterion("return_url <", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlLessThanOrEqualTo(String value) {
            addCriterion("return_url <=", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlLike(String value) {
            addCriterion("return_url like", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlNotLike(String value) {
            addCriterion("return_url not like", value, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlIn(List<String> values) {
            addCriterion("return_url in", values, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlNotIn(List<String> values) {
            addCriterion("return_url not in", values, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlBetween(String value1, String value2) {
            addCriterion("return_url between", value1, value2, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andReturnUrlNotBetween(String value1, String value2) {
            addCriterion("return_url not between", value1, value2, "returnUrl");
            return (Criteria) this;
        }

        public Criteria andExpiredTimeIsNull() {
            addCriterion("expired_time is null");
            return (Criteria) this;
        }

        public Criteria andExpiredTimeIsNotNull() {
            addCriterion("expired_time is not null");
            return (Criteria) this;
        }

        public Criteria andExpiredTimeEqualTo(Date value) {
            addCriterion("expired_time =", value, "expiredTime");
            return (Criteria) this;
        }

        public Criteria andExpiredTimeNotEqualTo(Date value) {
            addCriterion("expired_time <>", value, "expiredTime");
            return (Criteria) this;
        }

        public Criteria andExpiredTimeGreaterThan(Date value) {
            addCriterion("expired_time >", value, "expiredTime");
            return (Criteria) this;
        }

        public Criteria andExpiredTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("expired_time >=", value, "expiredTime");
            return (Criteria) this;
        }

        public Criteria andExpiredTimeLessThan(Date value) {
            addCriterion("expired_time <", value, "expiredTime");
            return (Criteria) this;
        }

        public Criteria andExpiredTimeLessThanOrEqualTo(Date value) {
            addCriterion("expired_time <=", value, "expiredTime");
            return (Criteria) this;
        }

        public Criteria andExpiredTimeIn(List<Date> values) {
            addCriterion("expired_time in", values, "expiredTime");
            return (Criteria) this;
        }

        public Criteria andExpiredTimeNotIn(List<Date> values) {
            addCriterion("expired_time not in", values, "expiredTime");
            return (Criteria) this;
        }

        public Criteria andExpiredTimeBetween(Date value1, Date value2) {
            addCriterion("expired_time between", value1, value2, "expiredTime");
            return (Criteria) this;
        }

        public Criteria andExpiredTimeNotBetween(Date value1, Date value2) {
            addCriterion("expired_time not between", value1, value2, "expiredTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeIsNull() {
            addCriterion("success_time is null");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeIsNotNull() {
            addCriterion("success_time is not null");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeEqualTo(Date value) {
            addCriterion("success_time =", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeNotEqualTo(Date value) {
            addCriterion("success_time <>", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeGreaterThan(Date value) {
            addCriterion("success_time >", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("success_time >=", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeLessThan(Date value) {
            addCriterion("success_time <", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeLessThanOrEqualTo(Date value) {
            addCriterion("success_time <=", value, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeIn(List<Date> values) {
            addCriterion("success_time in", values, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeNotIn(List<Date> values) {
            addCriterion("success_time not in", values, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeBetween(Date value1, Date value2) {
            addCriterion("success_time between", value1, value2, "successTime");
            return (Criteria) this;
        }

        public Criteria andSuccessTimeNotBetween(Date value1, Date value2) {
            addCriterion("success_time not between", value1, value2, "successTime");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pay_order
     *
     * @mbg.generated do_not_delete_during_merge Tue Oct 10 17:14:16 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}