package net.ltsoftware.usercenter.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.id
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.QQ_OPENID
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private String qqOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.WX_OPENID
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private String wxOpenid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.AVATAR
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.ACCOUNT
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private String account;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.PASSWORD
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.SALT
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.NAME
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.BIRTHDAY
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.SEX
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.EMAIL
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.PHONE
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.STATUS
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.CREATE_TIME
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.UPDATE_TIME
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.VERSION
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private Integer version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column acc_user.BALANCE
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    private Integer balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.id
     *
     * @return the value of acc_user.id
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.id
     *
     * @param id the value for acc_user.id
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.QQ_OPENID
     *
     * @return the value of acc_user.QQ_OPENID
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public String getQqOpenid() {
        return qqOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.QQ_OPENID
     *
     * @param qqOpenid the value for acc_user.QQ_OPENID
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setQqOpenid(String qqOpenid) {
        this.qqOpenid = qqOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.WX_OPENID
     *
     * @return the value of acc_user.WX_OPENID
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public String getWxOpenid() {
        return wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.WX_OPENID
     *
     * @param wxOpenid the value for acc_user.WX_OPENID
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setWxOpenid(String wxOpenid) {
        this.wxOpenid = wxOpenid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.AVATAR
     *
     * @return the value of acc_user.AVATAR
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.AVATAR
     *
     * @param avatar the value for acc_user.AVATAR
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.ACCOUNT
     *
     * @return the value of acc_user.ACCOUNT
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.ACCOUNT
     *
     * @param account the value for acc_user.ACCOUNT
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.PASSWORD
     *
     * @return the value of acc_user.PASSWORD
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.PASSWORD
     *
     * @param password the value for acc_user.PASSWORD
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.SALT
     *
     * @return the value of acc_user.SALT
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.SALT
     *
     * @param salt the value for acc_user.SALT
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setSalt(String salt) {
        this.salt = salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.NAME
     *
     * @return the value of acc_user.NAME
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.NAME
     *
     * @param name the value for acc_user.NAME
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.BIRTHDAY
     *
     * @return the value of acc_user.BIRTHDAY
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.BIRTHDAY
     *
     * @param birthday the value for acc_user.BIRTHDAY
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.SEX
     *
     * @return the value of acc_user.SEX
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.SEX
     *
     * @param sex the value for acc_user.SEX
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.EMAIL
     *
     * @return the value of acc_user.EMAIL
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.EMAIL
     *
     * @param email the value for acc_user.EMAIL
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.PHONE
     *
     * @return the value of acc_user.PHONE
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.PHONE
     *
     * @param phone the value for acc_user.PHONE
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.STATUS
     *
     * @return the value of acc_user.STATUS
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.STATUS
     *
     * @param status the value for acc_user.STATUS
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.CREATE_TIME
     *
     * @return the value of acc_user.CREATE_TIME
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.CREATE_TIME
     *
     * @param createTime the value for acc_user.CREATE_TIME
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.UPDATE_TIME
     *
     * @return the value of acc_user.UPDATE_TIME
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.UPDATE_TIME
     *
     * @param updateTime the value for acc_user.UPDATE_TIME
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.VERSION
     *
     * @return the value of acc_user.VERSION
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.VERSION
     *
     * @param version the value for acc_user.VERSION
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column acc_user.BALANCE
     *
     * @return the value of acc_user.BALANCE
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public Integer getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column acc_user.BALANCE
     *
     * @param balance the value for acc_user.BALANCE
     *
     * @mbg.generated Mon Sep 09 18:26:50 CST 2019
     */
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
}