package net.ltsoftware.usercenter.dao;

import java.util.List;
import net.ltsoftware.usercenter.model.PayOrder;
import net.ltsoftware.usercenter.model.PayOrderExample;
import org.apache.ibatis.annotations.Param;

public interface PayOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    long countByExample(PayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    int deleteByExample(PayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    int insert(PayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    int insertSelective(PayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    List<PayOrder> selectByExampleWithBLOBs(PayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    List<PayOrder> selectByExample(PayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    PayOrder selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    int updateByExampleSelective(@Param("record") PayOrder record, @Param("example") PayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") PayOrder record, @Param("example") PayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    int updateByExample(@Param("record") PayOrder record, @Param("example") PayOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    int updateByPrimaryKeySelective(PayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(PayOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_pay_order
     *
     * @mbg.generated Tue Oct 10 17:14:16 CST 2023
     */
    int updateByPrimaryKey(PayOrder record);
}