package net.ltsoftware.usercenter.dao;

import net.ltsoftware.usercenter.model.Trade;
import net.ltsoftware.usercenter.model.TradeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_trade
     *
     * @mbg.generated Wed Sep 11 16:15:59 CST 2019
     */
    long countByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_trade
     *
     * @mbg.generated Wed Sep 11 16:15:59 CST 2019
     */
    int deleteByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_trade
     *
     * @mbg.generated Wed Sep 11 16:15:59 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_trade
     *
     * @mbg.generated Wed Sep 11 16:15:59 CST 2019
     */
    int insert(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_trade
     *
     * @mbg.generated Wed Sep 11 16:15:59 CST 2019
     */
    int insertSelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_trade
     *
     * @mbg.generated Wed Sep 11 16:15:59 CST 2019
     */
    List<Trade> selectByExample(TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_trade
     *
     * @mbg.generated Wed Sep 11 16:15:59 CST 2019
     */
    Trade selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_trade
     *
     * @mbg.generated Wed Sep 11 16:15:59 CST 2019
     */
    int updateByExampleSelective(@Param("record") Trade record, @Param("example") TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_trade
     *
     * @mbg.generated Wed Sep 11 16:15:59 CST 2019
     */
    int updateByExample(@Param("record") Trade record, @Param("example") TradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_trade
     *
     * @mbg.generated Wed Sep 11 16:15:59 CST 2019
     */
    int updateByPrimaryKeySelective(Trade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table acc_trade
     *
     * @mbg.generated Wed Sep 11 16:15:59 CST 2019
     */
    int updateByPrimaryKey(Trade record);
}